services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_blockchain
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./dotenv_file/.env
volumes:
  mongodb_data:
